    public enum BattleSceneSounds {
        DrawAndInspect,
        Footsteps,
        HealApplied,
        HitCritical,
        HitEffective,
        KillSound,
        PlayerDefeat,
        PlayerVictory,
        SkillGeneral,
        SuperCritical,
        BlockSuccess,
        BuffApplied,
        UIClick,
        UIPanelClose,
        UIPanelOpen,
        Chargeup,
        DebuffApplied,
        CritPower,
        CanteenDrop,
        CanteenGrab,
        CanteenUse,
        ShieldHit,
        ShieldActivate
    }
    public enum BattleSceneMusic {
        BattleTheme,
        BossTheme
    }
